name: Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ^1.24
      id: go


    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Run tests
      run: |
        go vet .
        go test ./...
        go test -c github.com/google/nftables
        sudo ./nftables.test -test.v -run_system_tests
        go test -c github.com/google/nftables/integration
        (cd integration && sudo ../integration.test -test.v -run_system_tests)
